### PR TITLE
Golang

### PR DESCRIPTION
**Pull request by benoitmasson**
Rewrite of the Java code as Go code.

The same structure was used for classes, attributes and methods (and their visibility), and for tests (a single functional test with a complete usage scenario).

### CODE REVIEW

**Comment by SamirTalwar** [comment]
Looks good. Is there a reason you copied *README.md* as *golang/TODO.md*?

**Comment by benoitmasson** [comment]
I wanted it there to give the exercise, but you are right, it may not be useful in this repository. Do you want me to remove it?

**Comment by SamirTalwar** [comment]
Yeah, I think so. Duplication can cause problems down the line. Don’t want them getting out of sync. 🙃

**Comment by benoitmasson** [comment]
Done! (actually, just removed the last commit)

**Comment by SamirTalwar** [comment]
Cool, thanks!

**Pull request merged**
